api_provider: openalex
base_path: D:\OpenAlexProject\fakenewscitationnetwork\libraries\testingbugfixes
created_at: '2025-10-09T11:15:45.670672'
description: testing da bug fixes
name: testingbugfixes
